name: MCTManager
version: '${version}'
main: org.braekpo1nt.mctmanager.Main
description: The plugin that manages MCT
author: Braekpo1nt
api-version: 1.19


commands:
  mcttest:
    description: Test the command
    usage: "/mctest"
    permission: mctmanager.mcttest
    permission-message: "You do not have permission to use this command"
  mctmvtest:
    description: Test the multiverse world integration
    usage: "/mctmvtest"
    permission: mctmanager.mctmvtest
    permission-message: "You do not have permission to use this command"
  