name: MCTManager
version: '${version}'
main: org.braekpo1nt.mctmanager.Main
description: The plugin that manages MCT
author: Braekpo1nt
api-version: 1.19

depend: [Multiverse-Core]


commands:
  mct:
    description: The command for managing Minecraft Tournament (MCT)
    usage: "/mct <option>"
    permission: mctmanager.mct
    permission-message: "You do not have permission to use this command"
  mctdebug:
    description: Debug command
    usage: "/debug <args>"
    permission: mctmanager.mctdebug
    permission-message: "You do not have permission to use this command"
  