name: MCTManager
version: '${version}'
main: org.braekpo1nt.mctmanager.Main
description: The plugin that manages MCT
author: Braekpo1nt
api-version: 1.19

depend: [packetevents]
softdepend: [LuckPerms, DecentHolograms, Multiverse-Core]

commands:
  mct:
    description: The command for managing Minecraft Tournament (MCT)
    usage: "/mct <option>"
    permission: mctmanager.mct
    permission-message: "You do not have permission to use this command"
  mctdebug:
    description: Debug command
    usage: "/debug <args>"
    permission: mctmanager.mctdebug
    permission-message: "You do not have permission to use this command"
  utils:
    description: Utilities useful for working with MCT
    permission: mctmanager.utils
    permission-message: "You do not have permission to use this command"
  readyup:
    description: Signal that you are ready for the event to begin
    permission: mctmanager.readyup
    permission-message: "You do not have permission to use this command"
  unready:
    description: Signal that you are not ready for the event to begin
    permission: mctmanager.unready
    permission-message: "You do not have permission to use this command"
  top:
    description: Teleports the user to the highest solid block above their position
    permission: mctmanager.top
    permission-message: "You do not have permission to use this command"
  t:
    description: Send a message to your teammates
    permission: mctmanager.t
    permission-message: "You do not have permission to use this command"
  bugreport:
    description: Report a bug
    usage: "/bugreport <description>"
    permission: mctmanager.bugreport
    permission-message: "You do not have permission to use this command"
  notready:
    description: Indicate your are not ready for the event to continue
    usage: "/notready <reason>"
    permission: mctmanager.notready
    permission-message: "You do not have permission to use this command"
