name: MCTManager
version: '${version}'
main: org.braekpo1nt.mctmanager.Main
description: The plugin that manages MCT
author: Braekpo1nt
api-version: 1.19


commands:
  mcttest:
    description: Test the command
    permission: mctmanager.mcttest
    permission-message: "You do not have permission to use this command"